# --------------------------------------------------
# Site settings
title: Since Town Hall
description: How long has it been since your representative's last town hall?
owner: http://github.com/averyj
repo: sincetownhall
branch: gh-pages

# --------------------------------------------------
# Site imagery
favicon: /ui/img/graph/sincetownhall-favicon.png
avatar: /ui/img/graph/sincetownhall-avatar.png
poster: /ui/img/graph/sincetownhall-poster.jpg
#twitter: sincetownhall
#facebook: sincetownhall

# --------------------------------------------------
# the subpath of your site, e.g. /blog
baseurl: "/sincetownhall"
# css container
namespace: sincetownhall

# --------------------------------------------------
# Build settings
sass:
  style: compressed
  sass_dir: ui/_sass

collections:
  pages:
    output: true
    permalink: /:path/
  docs:
    output: true
    permalink: /docs/:path/
  styles:
    output: true
    permalink: /styles/:path/
  representatives:
    output: true
    permalink: /representatives/:path/
  states:
    output: true
    permalink: /states/:path/

defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
-
  scope:
    path: ""
    type: "docs"
  values:
    layout: "doc"
-
  scope:
    path: ""
    type: "representatives"
  values:
    layout: "profile"
-
  scope:
    path: ""
    type: "states"
  values:
    layout: "state"
